version: "3"

networks:
  ddbs_network:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    volumes:
      - ${PWD}/db-generation/articles:/buffer
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  historyserver:
    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  datanode2:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode2
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  datanode3:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode3
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      - ddbs_network

  ddbs_mongo_1:
    image: mongo:4.4.4
    container_name: ddbs_mongo_1
    volumes:
      - ${PWD}/ddbs_1_data:/data_load
    networks:
      - ddbs_network

  ddbs_mongo_2:
    image: mongo:4.4.4
    container_name: ddbs_mongo_2
    volumes:
      - ${PWD}/ddbs_2_data:/data_load
    networks:
      - ddbs_network

  ddbs_mongo_1_bak:
    image: mongo:4.4.4
    container_name: ddbs_mongo_1_bak
    volumes:
      - ${PWD}/ddbs_1_data:/data_load
    networks:
      - ddbs_network

  ddbs_mongo_2_bak:
    image: mongo:4.4.4
    container_name: ddbs_mongo_2_bak
    volumes:
      - ${PWD}/ddbs_2_data:/data_load
    networks:
      - ddbs_network

  python-app:
    build: .
    volumes:
      - ${PWD}/backend:/usr/src/app
    networks:
      - ddbs_network
    ports:
      - "8060:8060"
    depends_on:
      - ddbs_mongo_1
      - ddbs_mongo_2
      - ddbs_mongo_1_bak
      - ddbs_mongo_2_bak

